name: devops testing

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: 'Custom input for tags'
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set image tag
        run: |
          if [[ -z "${{inputs.tag}}" ]]; then
            echo "TAG is not provided, using latest"
            echo "TAG=${{ secrets.DOCKERHUB_USER }}/expertlab:latest" >> $GITHUB_ENV
          else
            echo "TAG is provided, using ${{inputs.tag}}"
            echo "TAG=${{ secrets.DOCKERHUB_USER }}/expertlab:latest,${{ secrets.DOCKERHUB_USER }}/expertlab:${{inputs.tag}}" >> $GITHUB_ENV
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.TAG }}
  custom-action:
    runs-on: ubuntu-latest
    steps:
      - name: run own action
        id: run-own
        uses: SandroBarillaPXL/expertlab-sprint1-action@v1.2.1
        with:
          input1: "ik geef een input1"
          #input2: "deze input is niet verplicht maar ik doe het toch"
      - name: use action output
        run: echo "The output of my action is ${{ steps.run-own.outputs.output1 }}"
